name: go-ws-sh-fe

on:
    push:
        branches: ["main"]

    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22.12.0"

            - name: Install dependencies
              run: |
                  npm install -g pnpm
                  pnpm install --force
            - run: cd password-hashed && npm install -g pnpm && pnpm install --force      
            - run: npm run test

            - run: npm run build
            - name: Static HTML export with Nuxt
              run: npm run generate
            - run: mkdir -v -p ./static
            - run: tar -czvf ./static/web-content.tgz -C dist --exclude=*.tgz .
            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/heads/main')
              with:
                  tag_name: Continuous-integration-${{ github.sha }}

                  files: |
                      ./static/*.tgz
