name: go-ws-sh-fe

on:
    push:
        branches: ["main"]

    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22.12.0"

            - name: Install dependencies
              run: |
                  corepack enable
                  corepack prepare yarn@4.7.0 --activate
                  yarn install --mode=update-lockfile
                  yarn install 
                  npm run test

            - run: npm run build
            - name: Static HTML export with Nuxt
              run: npm run generate
            - run: tar  zcvf -C dist --exclude=*.tgz ./dist/web-content.tgz ./* 
            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/heads/main')
              with:
                  tag_name: Continuous-integration-${{ github.sha }}

                  files: |
                      dist/*.tgz
